"""
Auto-generated configuration helper functions from shared_config.py
DO NOT EDIT THIS FILE MANUALLY - it will be overwritten on build
"""

from typing import Dict, Any
from .config_schema_generated import ConfigurationData, ALL_FIELDS


def log_configuration_update(logger, config: ConfigurationData) -> None:
    """Log configuration update with all field values"""
    logger.info(f"Updated lsfg-vk configuration: dll={config['dll']}, allow_fp16={config['allow_fp16']}, multiplier={config['multiplier']}, adaptive={config['adaptive']}, target_fps={config['target_fps']}, adaptive_max_multiplier={config['adaptive_max_multiplier']}, adaptive_stable_cadence={config['adaptive_stable_cadence']}, flow_scale={config['flow_scale']}, performance_mode={config['performance_mode']}, pacing={config['pacing']}, active_in={config['active_in']}, gpu={config['gpu']}")


def get_config_field_names() -> list[str]:
    """Get all configuration field names"""
    return ALL_FIELDS.copy()


def extract_config_values(config: ConfigurationData) -> Dict[str, Any]:
    """Extract configuration values as a dictionary"""
    return {field: config[field] for field in ALL_FIELDS}
