"""
Auto-generated configuration schema components from shared_config.py
DO NOT EDIT THIS FILE MANUALLY - it will be overwritten on build
"""

from typing import TypedDict, Dict, Any, Union
from enum import Enum
import sys
from pathlib import Path

# Import shared configuration constants
sys.path.insert(0, str(Path(__file__).parent.parent.parent))
from shared_config import CONFIG_SCHEMA_DEF, ConfigFieldType

# Field name constants for type-safe access
DLL = "dll"
ALLOW_FP16 = "allow_fp16"
FRAME_GENERATION_ENABLED = "frame_generation_enabled"
MULTIPLIER = "multiplier"
ADAPTIVE = "adaptive"
TARGET_FPS = "target_fps"
ADAPTIVE_MAX_MULTIPLIER = "adaptive_max_multiplier"
ADAPTIVE_STABLE_CADENCE = "adaptive_stable_cadence"
FLOW_SCALE = "flow_scale"
PERFORMANCE_MODE = "performance_mode"
PACING = "pacing"
ACTIVE_IN = "active_in"
GPU = "gpu"
DISABLE_LSFGVK = "disable_lsfgvk"
DISABLE_HDR_EXPOSURE = "disable_hdr_exposure"
DXVK_FRAME_RATE = "dxvk_frame_rate"
DISABLE_STEAMDECK_MODE = "disable_steamdeck_mode"
ENABLE_ZINK = "enable_zink"


class ConfigurationData(TypedDict):
    """Type-safe configuration data structure - AUTO-GENERATED"""
    dll: str
    allow_fp16: bool
    frame_generation_enabled: bool
    multiplier: int
    adaptive: bool
    target_fps: int
    adaptive_max_multiplier: int
    adaptive_stable_cadence: bool
    flow_scale: float
    performance_mode: bool
    pacing: str
    active_in: str
    gpu: str
    disable_lsfgvk: bool
    disable_hdr_exposure: bool
    dxvk_frame_rate: int
    disable_steamdeck_mode: bool
    enable_zink: bool


def get_script_parsing_logic():
    """Return the script parsing logic as a callable"""
    def parse_script_values(lines):
        script_values = {}
        for line in lines:
            line = line.strip()
            if not line or line.startswith("#") or not line.startswith("export "):
                continue
            if "=" in line:
                export_line = line[len("export "):]
                key, value = export_line.split("=", 1)
                key = key.strip()
                value = value.strip()

                # Auto-generated parsing logic:
                if key == "DISABLE_LSFGVK_EXPERIMENTAL":
                        script_values["disable_lsfgvk"] = value == "1"
                if key == "LSFGVK_DISABLE_HDR_EXPOSURE":
                        script_values["disable_hdr_exposure"] = value == "1"
                if key == "DXVK_FRAME_RATE":
                        try:
                            script_values["dxvk_frame_rate"] = int(value)
                        except ValueError:
                            pass
                if key == "SteamDeck":
                        script_values["disable_steamdeck_mode"] = value == "0"
                if key == "__GLX_VENDOR_LIBRARY_NAME" and value == "mesa":
                        script_values["enable_zink"] = True
                if key == "MESA_LOADER_DRIVER_OVERRIDE" and value == "zink":
                        script_values["enable_zink"] = True
                if key == "GALLIUM_DRIVER" and value == "zink":
                        script_values["enable_zink"] = True

        return script_values
    return parse_script_values


def get_script_generation_logic():
    """Return the script generation logic as a callable"""
    def generate_script_lines(config):
        lines = []
        if config.get("disable_lsfgvk", False):
            lines.append("export DISABLE_LSFGVK_EXPERIMENTAL=1")
        if config.get("disable_hdr_exposure", False):
            lines.append("export LSFGVK_DISABLE_HDR_EXPOSURE=1")
        dxvk_frame_rate = config.get("dxvk_frame_rate", 0)
        if dxvk_frame_rate > 0:
            lines.append(f"export DXVK_FRAME_RATE={dxvk_frame_rate}")
        if config.get("disable_steamdeck_mode", False):
            lines.append("export SteamDeck=0")
        if config.get("enable_zink", False):
            lines.append("export __GLX_VENDOR_LIBRARY_NAME=mesa")
            lines.append("export MESA_LOADER_DRIVER_OVERRIDE=zink")
            lines.append("export GALLIUM_DRIVER=zink")
        return lines
    return generate_script_lines


ALL_FIELDS = ['dll', 'allow_fp16', 'frame_generation_enabled', 'multiplier', 'adaptive', 'target_fps', 'adaptive_max_multiplier', 'adaptive_stable_cadence', 'flow_scale', 'performance_mode', 'pacing', 'active_in', 'gpu', 'disable_lsfgvk', 'disable_hdr_exposure', 'dxvk_frame_rate', 'disable_steamdeck_mode', 'enable_zink']
